plugin:
    name: 'initbiz.seostorm::lang.plugin.name'
    description: 'initbiz.seostorm::lang.plugin.description'
    author: Initbiz
    icon: icon-search

permissions:
    initbiz.seostorm.settings:
        tab: 'initbiz.seostorm::lang.permissions.settings_tab'
        label: 'initbiz.seostorm::lang.permissions.access_settings'
    initbiz.seostorm.settings.meta:
        tab: 'initbiz.seostorm::lang.permissions.settings_tab'
        label: 'initbiz.seostorm::lang.permissions.access_settings_meta'
    initbiz.seostorm.settings.sitemap:
        tab: 'initbiz.seostorm::lang.permissions.settings_tab'
        label: 'initbiz.seostorm::lang.permissions.access_settings_sitemap'
    initbiz.seostorm.settings.robots:
        tab: 'initbiz.seostorm::lang.permissions.settings_tab'
        label: 'initbiz.seostorm::lang.permissions.access_settings_robots'
    initbiz.seostorm.settings.favicon:
        tab: 'initbiz.seostorm::lang.permissions.settings_tab'
        label: 'initbiz.seostorm::lang.permissions.access_settings_favicon'
    initbiz.seostorm.settings.webmanifest:
        tab: 'initbiz.seostorm::lang.permissions.settings_tab'
        label: 'initbiz.seostorm::lang.permissions.access_settings_webmanifest'
    initbiz.seostorm.settings.social_media:
        tab: 'initbiz.seostorm::lang.permissions.settings_tab'
        label: 'initbiz.seostorm::lang.permissions.access_settings_social_media'
    initbiz.seostorm.settings.schema:
        tab: 'initbiz.seostorm::lang.permissions.settings_tab'
        label: 'initbiz.seostorm::lang.permissions.access_settings_schema'
    initbiz.seostorm.settings.migrate:
        tab: 'initbiz.seostorm::lang.permissions.settings_tab'
        label: 'initbiz.seostorm::lang.permissions.access_settings_migrate'
    initbiz.seostorm.htaccess:
        tab: 'initbiz.seostorm::lang.permissions.settings_tab'
        label: 'initbiz.seostorm::lang.permissions.access_htaccess'
    initbiz.seostorm.sitemapmedia:
        tab: 'initbiz.seostorm::lang.permissions.settings_tab'
        label: 'initbiz.seostorm::lang.permissions.sitemapmedia'
    initbiz.seostorm.sitemapitems:
        tab: 'initbiz.seostorm::lang.permissions.settings_tab'
        label: 'initbiz.seostorm::lang.permissions.sitemapitems'

