plugin:
    name: 'Initbiz SEO'
    description: 'Magically manage the SEO of your site'
    author: Initbiz
    icon: icon-search
permissions:
    initbiz.seo.config:
        tab: 'initbiz.seo::lang.plugin.name'
        label: 'Access Initbiz SEO configuration'
    initbiz.seo.og:
        tab: 'initbiz.seo::lang.plugin.name'
        label: 'Access Open Graph tab'
    initbiz.seo.sitemap:
        tab: 'initbiz.seo::lang.plugin.name'
        label: 'Access Sitemap tab'
    initbiz.seo.meta:
        tab: 'initbiz.seo::lang.plugin.name'
        label: 'Access Meta tab'
    initbiz.seo.schema:
        tab: 'initbiz.seo::lang.plugin.name'
        label: 'Access Schema tab'
