plugin:
    name: "Arcane SEO"
    description: 'Magically manage the SEO of your site'
    author: Arcane
    icon: icon-search
permissions:
    arcane.manage_seo:
        tab: SEO
        label: 'Manage SEO'
