media:
    label: Sitemap Media
    view:
        list: $/initbiz/seostorm/models/sitemapmedia/columns.yaml
        toolbarButtons: create|delete
        recordsPerPage: 10
    manage:
        form: $/initbiz/seostorm/models/sitemapmedia/fields.yaml
