images:
    label: initbiz.seostorm::lang.models.sitemap_item.images
    view:
        list:
            columns:
                loc:
                    label: initbiz.seostorm::lang.models.sitemap_media.loc
                    searchable: true
        toolbarButtons: remove
        recordUrl: initbiz/seostorm/sitemapmedia/update/:id
        recordsPerPage: 20

videos:
    label: initbiz.seostorm::lang.models.sitemap_item.videos
    view:
        list:
            columns:
                loc:
                    label: initbiz.seostorm::lang.models.sitemap_media.loc
                    searchable: true
        toolbarButtons: remove
        recordUrl: initbiz/seostorm/sitemapmedia/update/:id
        recordsPerPage: 20
