item:
    label: Invoice Line Item
    view:
        list: $/initbiz/seostorm/models/sitemapitem/columns.yaml
        toolbarButtons: create|delete
        recordsPerPage: 10
    manage:
        form: $/initbiz/seostorm/models/sitemapitem/fields.yaml
