# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Sitemap Media

# Model Form Field configuration
form: $/initbiz/seostorm/models/sitemapmedia/fields.yaml

# Model Class name
modelClass: Initbiz\Seostorm\Models\SitemapMedia

# Default redirect location
defaultRedirect: initbiz/seostorm/sitemapmedia

# Create page
create:
    title: backend::lang.form.create_title
    redirect: initbiz/seostorm/sitemapmedia/update/:id
    redirectClose: initbiz/seostorm/sitemapmedia

# Update page
update:
    title: backend::lang.form.update_title
    redirect: initbiz/seostorm/sitemapmedia
    redirectClose: initbiz/seostorm/sitemapmedia

# Preview page
preview:
    title: backend::lang.form.preview_title
