meta_title:
    property: meta_title
    label: initbiz.seostorm::lang.form.general.meta_title_label
    type: text
    span: full
    tab: initbiz.seostorm::lang.form.general.tab_meta
    trans: true
    attributes:
        data-counter: 1
        data-min: 30
        data-max: 60
        data-seo: title

meta_description:
    property: meta_description
    label: initbiz.seostorm::lang.form.general.meta_description_label
    type: textarea
    size: tiny
    span: full
    tab: initbiz.seostorm::lang.form.general.tab_meta
    cssClass: char-counter
    trans: true
    attributes:
        data-counter: 1
        data-min: 100
        data-max: 160
        data-seo: description

canonical_url:
    property: canonical_url
    label: initbiz.seostorm::lang.form.general.canonical_url_label
    type: text
    tab: initbiz.seostorm::lang.form.general.tab_meta
    span: full
    trans: true
    commentAbove: initbiz.seostorm::lang.form.general.canonical_url_comment

robot_index:
    property: robot_index
    label: initbiz.seostorm::lang.form.general.robot_index_label
    type: balloon-selector
    tab: initbiz.seostorm::lang.form.general.tab_meta
    options:
        index: index
        noindex: noindex
    commentAbove: initbiz.seostorm::lang.form.general.robot_index_comment
    span: left
    default: index

robot_follow:
    property: robot_follow
    label: initbiz.seostorm::lang.form.general.robot_follow_label
    type: balloon-selector
    tab: initbiz.seostorm::lang.form.general.tab_meta
    options:
        follow: follow
        nofollow: nofollow
    commentAbove: initbiz.seostorm::lang.form.general.robot_follow_comment
    span: right
    default: follow

robot_advanced:
    property: robot_advanced
    label: initbiz.seostorm::lang.form.general.robot_advanced_label
    tab: initbiz.seostorm::lang.form.general.tab_meta
    commentAbove: initbiz.seostorm::lang.form.general.robot_advanced_comment
    span: left
