og_title:
    label: initbiz.seostorm::lang.form.general.og_title_label
    tab: initbiz.seostorm::lang.form.general.tab_open_graph
    span: auto
    trans: true
    commentAbove: initbiz.seostorm::lang.form.general.og_title_comment
    placeholder: initbiz.seostorm::lang.form.general.og_title_placeholder
og_description:
    label: initbiz.seostorm::lang.form.general.og_description_label
    tab: initbiz.seostorm::lang.form.general.tab_open_graph
    type: textarea
    size: tiny
    span: auto
    trans: true
    commentAbove: initbiz.seostorm::lang.form.general.og_description_comment
    placeholder: initbiz.seostorm::lang.form.general.og_description_placeholder

og_type:
    label: initbiz.seostorm::lang.form.general.og_type_label
    tab: initbiz.seostorm::lang.form.general.tab_open_graph
    span: auto
    placeholder: initbiz.seostorm::lang.form.general.og_type_placeholder

og_card:
    label: initbiz.seostorm::lang.form.general.og_card_label
    tab: initbiz.seostorm::lang.form.general.tab_open_graph
    type: dropdown
    options:
        summary-large-image: summary-large-image
        summary: summary
        app: app
        player: player
    default: summary-large-image
    span: left

og_image:
    label: initbiz.seostorm::lang.form.general.og_image_label
    type: mediafinder
    mode: image
    tab: initbiz.seostorm::lang.form.general.tab_open_graph
    span: auto
    commentAbove: initbiz.seostorm::lang.form.general.og_image_comment

og_ref_image:
    label: initbiz.seostorm::lang.form.general.og_ref_image_label
    tab: initbiz.seostorm::lang.form.general.tab_open_graph
    span: auto
    placeholder: initbiz.seostorm::lang.form.general.og_ref_image_placeholder
    commentAbove: initbiz.seostorm::lang.form.general.og_ref_image_comment
