og_title:
    label: og:title (dynamic)
    tab: Open Graph
    span: auto
    trans: true
    comment: Recommended 50-60 characters
    placeholder: Defaults to SEO if left blank

og_description:
    label: og:description (dynamic)
    tab: Open Graph
    type: textarea
    size: tiny
    span: auto
    trans: true
    comment: The optimal length is 155
    placeholder: Defaults to SEO if left blank

og_type:
    label: og:type (dynamic)
    tab: Open Graph
    span: auto
    placeholder: website article video etc...

og_image:
    label: og:image
    type: mediafinder
    mode: image
    tab: Open Graph
    span: auto
    comment:

og_ref_image:
    label: og:image (dynamic)
    tab: Open Graph
    span: auto
    placeholder: "{{ example.image }}"
    comment: This will take priority over og:image
