meta_title:
    label: initbiz.seostorm::lang.form.general.meta_title_label
    type: text
    span: full
    tab: initbiz.seostorm::lang.form.general.tab_meta
    comment: initbiz.seostorm::lang.form.general.meta_title_comment
    trans: true
    attributes:
        data-counter: 1
        data-min: 30
        data-max: 60
        data-seo: title

meta_description:
    label: initbiz.seostorm::lang.form.general.meta_description_label
    type: textarea
    size: tiny
    span: full
    tab: initbiz.seostorm::lang.form.general.tab_meta
    cssClass: char-counter
    comment: initbiz.seostorm::lang.form.general.meta_description_comment
    trans: true
    attributes:
        data-counter: 1
        data-min: 100
        data-max: 160
        data-seo: description

canonical_url:
    label: initbiz.seostorm::lang.form.general.canonical_url_label
    type: text
    tab: initbiz.seostorm::lang.form.general.tab_meta
    span: full
    trans: true
    comment: initbiz.seostorm::lang.form.general.canonical_url_comment

robot_index:
    label: initbiz.seostorm::lang.form.general.robot_index_label
    type: balloon-selector
    tab: initbiz.seostorm::lang.form.general.tab_meta
    options:
        index: index
        noindex: noindex
    comment: initbiz.seostorm::lang.form.general.robot_index_comment
    span: left
    default: index

robot_follow:
    label: initbiz.seostorm::lang.form.general.robot_follow_label
    type: balloon-selector
    tab: initbiz.seostorm::lang.form.general.tab_meta
    options:
        follow: follow
        nofollow: nofollow
    comment: initbiz.seostorm::lang.form.general.robot_follow_comment
    span: right
    default: follow

robot_advanced:
    label: initbiz.seostorm::lang.form.general.robot_advanced_label
    tab: initbiz.seostorm::lang.form.general.tab_meta
    comment: initbiz.seostorm::lang.form.general.robot_advanced_comment
    span: left

enabled_in_sitemap:
    label: initbiz.seostorm::lang.form.general.enabled_in_sitemap_label
    comment: initbiz.seostorm::lang.form.general.enabled_in_sitemap_comment
    type: checkbox
    tab: initbiz.seostorm::lang.form.general.sitemap
    span: left
    default: true

model_class:
    label: initbiz.seostorm::lang.form.general.enabled_in_sitemap_label
    type: text
    span: right
    comment: initbiz.seostorm::lang.form.general.enabled_in_sitemap_comment
    placeholder: initbiz.seostorm::lang.form.general.model_class_placeholder
    tab: initbiz.seostorm::lang.form.general.sitemap

use_updated_at:
    label: initbiz.seostorm::lang.form.general.use_updated_at_label
    commentHtml: true
    comment: initbiz.seostorm::lang.form.general.use_updated_at_comment
    type: checkbox
    tab: initbiz.seostorm::lang.form.general.sitemap
    default: true

lastmod:
    label: initbiz.seostorm::lang.form.general.lastmod_label
    type: datepicker
    mode: datetime
    tab: initbiz.seostorm::lang.form.general.sitemap
    span: full
    trigger:
        action: hide
        field: settings[use_updated_at]
        condition: checked
    comment: initbiz.seostorm::lang.form.general.lastmod_comment

changefreq:
    label: initbiz.seostorm::lang.form.general.changefreq_label
    type: dropdown
    tab: initbiz.seostorm::lang.form.general.sitemap
    options:
        always: always
        hourly: hourly
        weekly: weekly
        monthly: monthly
        yearly: yearly
        never: never
    span: left
    comment: initbiz.seostorm::lang.form.general.changefreq_comment

priority:
    label: initbiz.seostorm::lang.form.general.priority_label
    type: dropdown
    tab: initbiz.seostorm::lang.form.general.sitemap
    options:
        0.1: 0.1
        0.2: 0.2
        0.3: 0.3
        0.4: 0.4
        0.5: 0.5
        0.6: 0.6
        0.7: 0.7
        0.8: 0.8
        0.9: 0.9
        1.0: 1.0
    span: right
    comment: initbiz.seostorm::lang.form.general.priority_comment
schemas:
    label: initbiz.seostorm::lang.form.general.schemas_label
    type: codeeditor
    size: giant
    stretch: true
    tab: initbiz.seostorm::lang.form.general.schemas
og_title:
    label: initbiz.seostorm::lang.form.general.og_title_label
    tab: initbiz.seostorm::lang.form.general.open_graph
    span: auto
    trans: true
    comment: initbiz.seostorm::lang.form.general.og_title_comment
    placeholder: initbiz.seostorm::lang.form.general.og_title_placeholder
og_description:
    label: initbiz.seostorm::lang.form.general.og_description_label
    tab: initbiz.seostorm::lang.form.general.open_graph
    type: textarea
    size: tiny
    span: auto
    trans: true
    comment: initbiz.seostorm::lang.form.general.og_description_comment
    placeholder: initbiz.seostorm::lang.form.general.og_description_placeholder

og_type:
    label: initbiz.seostorm::lang.form.general.og_type_label
    tab: Open Graph
    tab: initbiz.seostorm::lang.form.general.open_graph
    span: auto
    placeholder: initbiz.seostorm::lang.form.general.og_type_placeholder

og_image:
    label: initbiz.seostorm::lang.form.general.og_image_label
    type: mediafinder
    mode: image
    tab: Open Graph
    tab: initbiz.seostorm::lang.form.general.open_graph
    span: auto
    comment: initbiz.seostorm::lang.form.general.og_image_comment

og_ref_image:
    label: initbiz.seostorm::lang.form.general.og_ref_image_label
    tab: Open Graph
    tab: initbiz.seostorm::lang.form.general.open_graph
    span: auto
    placeholder: initbiz.seostorm::lang.form.general.og_ref_image_placeholder
    comment: initbiz.seostorm::lang.form.general.og_ref_image_comment
