enabled_in_sitemap:
    label: initbiz.seostorm::lang.form.general.enabled_in_sitemap_label
    comment: initbiz.seostorm::lang.form.general.enabled_in_sitemap_comment
    type: checkbox
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
    span: left
    default: true

use_updated_at:
    label: initbiz.seostorm::lang.form.general.use_updated_at_label
    commentHtml: true
    span: right
    comment: initbiz.seostorm::lang.form.general.use_updated_at_comment
    type: checkbox
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
    default: true

lastmod:
    label: initbiz.seostorm::lang.form.general.lastmod_label
    type: datepicker
    mode: datetime
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
    span: full
    trigger:
        action: hide
        field: use_updated_at
        condition: checked
    comment: initbiz.seostorm::lang.form.general.lastmod_comment

changefreq:
    label: initbiz.seostorm::lang.form.general.changefreq_label
    type: dropdown
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
    options:
        always: always
        hourly: hourly
        weekly: weekly
        monthly: monthly
        yearly: yearly
        never: never
    span: left
    comment: initbiz.seostorm::lang.form.general.changefreq_comment

priority:
    label: initbiz.seostorm::lang.form.general.priority_label
    type: dropdown
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
    options:
        0.1: 0.1
        0.2: 0.2
        0.3: 0.3
        0.4: 0.4
        0.5: 0.5
        0.6: 0.6
        0.7: 0.7
        0.8: 0.8
        0.9: 0.9
        1.0: 1.0
    span: right
    comment: initbiz.seostorm::lang.form.general.priority_comment

model_class:
    label: initbiz.seostorm::lang.form.general.model_class
    type: text
    span: left
    comment: initbiz.seostorm::lang.form.general.model_class_comment
    placeholder: initbiz.seostorm::lang.form.general.model_class_placeholder
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
