enabled_in_sitemap:
    label: initbiz.seostorm::lang.form.general.enabled_in_sitemap_label
    commentAbove: initbiz.seostorm::lang.form.general.enabled_in_sitemap_comment
    type: checkbox
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
    span: left
    default: true

use_updated_at:
    label: initbiz.seostorm::lang.form.general.use_updated_at_label
    commentHtml: true
    span: right
    commentAbove: initbiz.seostorm::lang.form.general.use_updated_at_comment
    type: checkbox
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
    default: true
    trigger:
        action: show
        field: enabled_in_sitemap
        condition: checked

lastmod:
    label: initbiz.seostorm::lang.form.general.lastmod_label
    type: datepicker
    mode: datetime
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
    span: full
    trigger:
        action: hide
        field: use_updated_at
        condition: checked
    commentAbove: initbiz.seostorm::lang.form.general.lastmod_comment

changefreq:
    label: initbiz.seostorm::lang.form.general.changefreq_label
    type: dropdown
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
    options:
        always: always
        hourly: hourly
        weekly: weekly
        monthly: monthly
        yearly: yearly
        never: never
    span: left
    commentAbove: initbiz.seostorm::lang.form.general.changefreq_comment
    trigger:
        action: show
        field: enabled_in_sitemap
        condition: checked

priority:
    label: initbiz.seostorm::lang.form.general.priority_label
    type: dropdown
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
    options:
        0.1: 0.1
        0.2: 0.2
        0.3: 0.3
        0.4: 0.4
        0.5: 0.5
        0.6: 0.6
        0.7: 0.7
        0.8: 0.8
        0.9: 0.9
        1.0: 1.0
    span: right
    commentAbove: initbiz.seostorm::lang.form.general.priority_comment
    trigger:
        action: show
        field: enabled_in_sitemap
        condition: checked

model_class:
    label: initbiz.seostorm::lang.form.general.model_class_label
    type: text
    span: left
    commentAbove: initbiz.seostorm::lang.form.general.model_class_comment
    placeholder: initbiz.seostorm::lang.form.general.model_class_placeholder
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
    trigger:
        action: show
        field: enabled_in_sitemap
        condition: checked

model_scope:
    label: initbiz.seostorm::lang.form.general.model_scope_label
    type: text
    span: right
    commentAbove: initbiz.seostorm::lang.form.general.model_scope_comment
    placeholder: initbiz.seostorm::lang.form.general.model_scope_placeholder
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
    trigger:
        action: show
        field: enabled_in_sitemap
        condition: checked

model_params:
    label: initbiz.seostorm::lang.form.general.model_params_label
    type: repeater
    span: full
    commentAbove: initbiz.seostorm::lang.form.general.model_params_comment
    tab: initbiz.seostorm::lang.form.general.tab_sitemap
    trigger:
        action: show
        field: enabled_in_sitemap
        condition: checked
    form:
        fields:
            param:
                label: initbiz.seostorm::lang.form.general.model_params_param_label
                placeholder: initbiz.seostorm::lang.form.general.model_params_param_placeholder
                span: left
            get_from:
                label: initbiz.seostorm::lang.form.general.model_params_get_from_label
                placeholder: initbiz.seostorm::lang.form.general.model_params_get_from_placeholder
                span: right

